# Generated by Django 4.0.4 on 2022-08-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linkGh',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
