# Generated by Django 4.0.4 on 2022-08-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_project_linkgh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='linkGh',
            new_name='linkgit',
        ),
    ]
